name: analyse

on: ["push", "pull_request"]

jobs:
    analyse:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                include:
                    - php: "8.2"
                      stability: "stable"
                    - php: "8.3"
                      stability: "stable"
                    - php: "8.4"
                      stability: "nightly"

        name: PHP ${{ matrix.php }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  stability: ${{ matrix.stability }}
                  extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
                  coverage: none

            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist --no-progress

            - name: Execute analysis
              run: composer analyse
